train:
  spectrogram:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: src.transforms.spec_augs.TimeMasking
        prob: 0.3
        time_mask_param: 40
      - _target_: src.transforms.spec_augs.FreqMasking
        prob: 0.3
        freq_mask_param: 40

