train:
  get_spectrogram: # special key for getting spectrogram
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
  audio: # name of the tensor on which we apply transform
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.wav_augs.Gain
      # - _target_: src.transforms.wav_augs.PitchShift
      # - _target_: src.transforms.wav_augs.PeakNormalization
      # - _target_: src.transforms.wav_augs.LowPassFilter
      # - _target_: src.transforms.wav_augs.BackgroundNoise
inference:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
